`timescale 1ns/1ps

module i3c_ctrl_inventory #(
    parameter integer MAX_ENDPOINTS = 8,
    parameter [6:0]  DYN_ADDR_BASE  = 7'h10
) (
    input  wire                           clk,
    input  wire                           rst_n,
    input  wire                           clear_tables,
    input  wire                           default_endpoint_enable,
    input  wire [7:0]                     default_service_period,
    input  wire                           schedule_tick,

    input  wire                           discover_valid,
    input  wire [47:0]                    discover_pid,
    input  wire [7:0]                     discover_bcr,
    input  wire [7:0]                     discover_dcr,

    input  wire                           broadcast_event_set_valid,
    input  wire                           broadcast_event_clear_valid,
    input  wire [7:0]                     broadcast_event_mask,

    input  wire                           direct_event_set_valid,
    input  wire                           direct_event_clear_valid,
    input  wire [6:0]                     direct_event_addr,
    input  wire [7:0]                     direct_event_mask,

    input  wire                           enable_update_valid,
    input  wire [6:0]                     enable_update_addr,
    input  wire                           enable_update_value,

    input  wire                           reset_action_update_valid,
    input  wire [6:0]                     reset_action_update_addr,
    input  wire [7:0]                     reset_action_update_value,

    input  wire                           status_update_valid,
    input  wire [6:0]                     status_update_addr,
    input  wire [15:0]                    status_update_value,
    input  wire                           status_update_ok,

    input  wire                           service_period_update_valid,
    input  wire [6:0]                     service_period_update_addr,
    input  wire [7:0]                     service_period_update_value,

    input  wire                           service_len_update_valid,
    input  wire [6:0]                     service_len_update_addr,
    input  wire [7:0]                     service_len_update_value,

    input  wire                           service_selector_update_valid,
    input  wire [6:0]                     service_selector_update_addr,
    input  wire [7:0]                     service_selector_update_value,

    input  wire                           service_result_valid,
    input  wire [6:0]                     service_result_addr,
    input  wire                           service_result_nack,

    input  wire [6:0]                     query_addr,
    output wire                           query_found,
    output wire [47:0]                    query_pid,
    output wire [7:0]                     query_bcr,
    output wire [7:0]                     query_dcr,
    output wire [1:0]                     query_class,
    output wire                           query_enabled,
    output wire                           query_health_fault,
    output wire                           query_last_seen_ok,
    output wire [7:0]                     query_event_mask,
    output wire [7:0]                     query_reset_action,
    output wire [15:0]                    query_status,
    output wire [7:0]                     query_service_period,
    output wire [7:0]                     query_service_rx_len,
    output wire [7:0]                     query_service_selector,
    output wire [15:0]                    query_service_count,
    output wire [15:0]                    query_success_count,
    output wire [15:0]                    query_error_count,
    output wire [7:0]                     query_consecutive_failures,
    output wire [15:0]                    query_last_service_tag,
    output wire                           query_due_now,

    input  wire [$clog2(MAX_ENDPOINTS)-1:0] scan_index,
    output wire                           scan_valid,
    output wire [6:0]                     scan_addr,
    output wire [1:0]                     scan_class,
    output wire                           scan_enabled,
    output wire                           scan_health_fault,
    output wire                           scan_due,
    output wire [7:0]                     scan_service_rx_len,
    output wire [7:0]                     scan_service_selector,

    output wire                           assign_valid,
    output wire [6:0]                     assign_dynamic_addr,
    output wire [$clog2(MAX_ENDPOINTS):0] daa_endpoint_count,
    output wire                           daa_table_full,
    output wire                           duplicate_pid,
    output wire [47:0]                    last_pid,
    output wire [7:0]                     last_bcr,
    output wire [7:0]                     last_dcr,

    output wire [$clog2(MAX_ENDPOINTS):0] policy_endpoint_count,
    output wire                           policy_table_full,
    output wire                           policy_update_miss,
    output wire [6:0]                     last_update_addr,
    output wire [7:0]                     last_event_mask
);

    i3c_ctrl_daa #(
        .MAX_ENDPOINTS(MAX_ENDPOINTS),
        .DYN_ADDR_BASE(DYN_ADDR_BASE)
    ) u_daa (
        .clk                (clk),
        .rst_n              (rst_n),
        .clear_table        (clear_tables),
        .discover_valid     (discover_valid),
        .discover_pid       (discover_pid),
        .discover_bcr       (discover_bcr),
        .discover_dcr       (discover_dcr),
        .assign_valid       (assign_valid),
        .assign_dynamic_addr(assign_dynamic_addr),
        .endpoint_count     (daa_endpoint_count),
        .table_full         (daa_table_full),
        .duplicate_pid      (duplicate_pid),
        .last_pid           (last_pid),
        .last_bcr           (last_bcr),
        .last_dcr           (last_dcr)
    );

    i3c_ctrl_policy #(
        .MAX_ENDPOINTS(MAX_ENDPOINTS)
    ) u_policy (
        .default_endpoint_enable(default_endpoint_enable),
        .default_service_period  (default_service_period),
        .clk                     (clk),
        .rst_n                   (rst_n),
        .clear_table             (clear_tables),
        .schedule_tick           (schedule_tick),
        .endpoint_add_valid      (assign_valid),
        .endpoint_dynamic_addr   (assign_dynamic_addr),
        .endpoint_pid            (last_pid),
        .endpoint_bcr            (last_bcr),
        .endpoint_dcr            (last_dcr),
        .broadcast_event_set_valid(broadcast_event_set_valid),
        .broadcast_event_clear_valid(broadcast_event_clear_valid),
        .broadcast_event_mask    (broadcast_event_mask),
        .direct_event_set_valid  (direct_event_set_valid),
        .direct_event_clear_valid(direct_event_clear_valid),
        .direct_event_addr       (direct_event_addr),
        .direct_event_mask       (direct_event_mask),
        .enable_update_valid     (enable_update_valid),
        .enable_update_addr      (enable_update_addr),
        .enable_update_value     (enable_update_value),
        .reset_action_update_valid(reset_action_update_valid),
        .reset_action_update_addr(reset_action_update_addr),
        .reset_action_update_value(reset_action_update_value),
        .status_update_valid     (status_update_valid),
        .status_update_addr      (status_update_addr),
        .status_update_value     (status_update_value),
        .status_update_ok        (status_update_ok),
        .service_period_update_valid(service_period_update_valid),
        .service_period_update_addr(service_period_update_addr),
        .service_period_update_value(service_period_update_value),
        .service_len_update_valid(service_len_update_valid),
        .service_len_update_addr (service_len_update_addr),
        .service_len_update_value(service_len_update_value),
        .service_selector_update_valid(service_selector_update_valid),
        .service_selector_update_addr(service_selector_update_addr),
        .service_selector_update_value(service_selector_update_value),
        .service_result_valid    (service_result_valid),
        .service_result_addr     (service_result_addr),
        .service_result_nack     (service_result_nack),
        .query_addr              (query_addr),
        .query_found             (query_found),
        .query_pid               (query_pid),
        .query_bcr               (query_bcr),
        .query_dcr               (query_dcr),
        .query_class             (query_class),
        .query_enabled           (query_enabled),
        .query_health_fault      (query_health_fault),
        .query_last_seen_ok      (query_last_seen_ok),
        .query_event_mask        (query_event_mask),
        .query_reset_action      (query_reset_action),
        .query_status            (query_status),
        .query_service_period    (query_service_period),
        .query_service_rx_len    (query_service_rx_len),
        .query_service_selector  (query_service_selector),
        .query_service_count     (query_service_count),
        .query_success_count     (query_success_count),
        .query_error_count       (query_error_count),
        .query_consecutive_failures(query_consecutive_failures),
        .query_last_service_tag  (query_last_service_tag),
        .query_due_now           (query_due_now),
        .scan_index              (scan_index),
        .scan_valid              (scan_valid),
        .scan_addr               (scan_addr),
        .scan_class              (scan_class),
        .scan_enabled            (scan_enabled),
        .scan_health_fault       (scan_health_fault),
        .scan_due                (scan_due),
        .scan_service_rx_len     (scan_service_rx_len),
        .scan_service_selector   (scan_service_selector),
        .endpoint_count          (policy_endpoint_count),
        .table_full              (policy_table_full),
        .policy_update_miss      (policy_update_miss),
        .last_update_addr        (last_update_addr),
        .last_event_mask         (last_event_mask)
    );
endmodule
